---
title: "Assignment 1"
author: "Thanh Nguyen"
date: "2026-09-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
Tesla_dataset <- read.csv("C:/Users/beanv/Downloads/tesla_vehicle_sales_performance.csv")
```

```{r}
#Categorical variables of Tesla dataset
table(Tesla_dataset$vehicle_model)

#Quantitative variables of Tesla dataset
summary(Tesla_dataset$average_vehicle_price_usd)
mean(Tesla_dataset$average_vehicle_price_usd)
sd(Tesla_dataset$average_vehicle_price_usd)

```

```{r}
#Transform varibale
Tesla_dataset$Price_Category <- ifelse(Tesla_dataset$average_vehicle_price_usd > 50000, "High", "Low")
```

```{r}
#plot one quantitative variable 
hist(Tesla_dataset$customer_rating, main = "Customer Rating's Distribution", xlab = "Customer Rating", col = "Blue", border = "black")
#This histogram was created based on "Customer Rating" to examine how this quantitative variable distrbute.
```

```{r}
#scatter plot
plot(Tesla_dataset$average_delivery_days, Tesla_dataset$customer_rating, pch = 19, xlab = "Average Delivery Time", ylab = "Customer Rating", main = "Customer Rating vs Delivery Time by Tesla Model")
#This scatter plot used two quantitative variables which are average delivery time and customer rating. The output are showing clearly the inverse relationship between two variables while higer delivery time match with low customer rating.
```

